/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function defineSchema(def: object): number
/**
 * schemaEncodeJson(id, jsonString) → Buffer  ← FASTEST ENCODE PATH
 * Call as: schema.encode(obj) where wrapper does JSON.stringify first
 */
export declare function schemaEncodeJson(schemaId: number, jsonStr: string): Buffer
/** schemaDecode → JSON string (JS does JSON.parse) ← FASTEST DECODE PATH */
export declare function schemaDecodeJson(schemaId: number, buf: Buffer): string
/** schemaGet → single field value as JS (50ns Rust side!) */
export declare function schemaGet(schemaId: number, buf: Buffer, fieldName: string): unknown
/** encodeJson(jsonString) → Buffer [schemaless, fast path] */
export declare function encodeJson(jsonStr: string): Buffer
/** decodeToJson(buf) → JSON string [schemaless, fast path] */
export declare function decodeToJson(buf: Buffer): string
/** validate */
export declare function validateBuf(buf: Buffer): boolean
